### ISSUE TITLE
is this the real MFSiNC?

### ISSUE THREAD

**Issue by thexkey** [MFSiNC/HAC#1]
i want to download the hac booty and hac phone.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBF+TpEoBCACewBcrrQaRGve/er1ASosJv4sRqoU86SorSMbkHQGYMYTJzdgL
otwtcEaSKWti7m6oA4nAe1gJcIWt8rTStGPpzSphRRyb+RsOweG2Kys2pW3auf3g
j34MKhrai0PvTFVlzjdl65EkOC0LBy2pJBt0D7c0hlE+KmL+0q9U6Lnev621Jdrq
NR93uk6zs/ySoBuN6Uz0vyK1RPBiW7EwdDCizoFCZMzrVAqWgSJXiC2YkdkMJXHx
DDeVmAx63GvaHd/SzQIk+86Qi3jWjlLyaYbDOUeTPo90w2fAUDZt/tmzoCuklz6A
Z0AOmrn0mkFNwnpf3048AmR5cpVCuatFMW7DABEBAAG0AIkBHAQQAQIABgUCX5Ok
SgAKCRCRYDYQa3NqF6h3B/4uSwfIGNCXJRAyFxAV7sI1UFXuMxPeHMdKXfeu6gjf
mw/SZWaFUIv/33s9O5rEOaibSMMY5jXk/bjzdQmGezon3UZZkT8SsCvjDENaVUGT
RRyZZTGRskVqvOT7G06p6imXe1faHlvdfthsIvOZwQiLJib+15uww25AH4se72ai
BrFfUA+lZseXYXrGMUHjYRFkp8rQeF0VZrJZKw/Pb66j5cKJDGV09cOK5Gx/DFdQ
eKW0SkHZuNkJ6NszFrr8/Kn827lJ335UvdFtQCloxTHHEw5IPhwDtJcTuwv1yh0r
CXgnXqphY3E9GFYxHXYq6Rn1W3rODo4O/C42zf0o74MN
=mNBh
-----END PGP PUBLIC KEY BLOCK-----

**Comment by MFSiNC** [comment]
the hac booty is publicly available, just look for it, i can't be arsed to upload it somewhere
 
![image](https://user-images.githubusercontent.com/72334284/97337408-7a5e3c80-183d-11eb-92cd-8ee834da5936.png)

**Comment by thexkey** [comment]
ok thanks

**Comment by brightersun99** [comment]
I have it. Do you want it still?

**Comment by samdisk11** [comment]
yes.

**Comment by samdisk11** [comment]
send me it? @brightersun99
