### ISSUE TITLE
Can't find modules source code

### ISSUE THREAD

**Issue by uRandomAlex** [MFSiNC/HAC#3]
I can't find modules source code... but README says:
> The source & project files are there if you want to compile them for your OS/platform.

**Comment by MFSiNC** [comment]
They're here on my GitHub
https://github.com/MFSiNC/VC

**Comment by uRandomAlex** [comment]
I can't find "pl_cvquery" source in your "VC" repository.

**Comment by MFSiNC** [comment]
I didn't write that one, its Blue Kirby's
https://facepunch.com/showthread.php?t=1311304

His links are dead though, I didn't keep the source.
